import Link from "next/link"
import { ArrowLeft } from "lucide-react"

export default function Contributors() {
  return (
    <div className="min-h-screen bg-white py-24 px-4">
      <div className="max-w-6xl mx-auto">
        <Link href="/" className="inline-flex items-center text-gray-500 mb-12 hover:text-gray-900">
          <ArrowLeft className="mr-2 h-4 w-4" /> Back to Home
        </Link>

        <h1 className="text-5xl font-serif font-bold mb-16 text-center tracking-tight">Contributors</h1>

        <div className="space-y-16">
          {contributors.map((contributor, index) => (
            <div key={index} className="bg-white rounded-lg shadow-sm overflow-hidden border border-gray-100">
              <div className="p-8 md:p-12">
                <h2 className="text-3xl font-serif font-bold mb-2 tracking-tight">{contributor.name}</h2>
                <p className="text-gray-500 mb-8 text-sm">ID: {contributor.id}</p>

                <div className="prose prose-lg max-w-none font-light leading-relaxed">
                  <h3 className="text-xl font-medium mb-4">{contributor.title}</h3>
                  {contributor.content.map((paragraph, i) => (
                    <p key={i}>{paragraph}</p>
                  ))}

                  {contributor.references && (
                    <>
                      <h4 className="text-lg font-medium mt-8 mb-4">References</h4>
                      <ul className="space-y-2 text-sm text-gray-700">
                        {contributor.references.map((ref, i) => (
                          <li key={i}>{ref}</li>
                        ))}
                      </ul>
                    </>
                  )}
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}

const contributors = [
  {
    name: "Shagota Islam Shudha",
    id: "24305052",
    title: "ANALYSIS OF ISRAEL-PALESTINE CONFLICT WITH CONFUCIUS ETHICS",
    content: [
      "Confucian ethical theory is developed by a Chinese philosopher, Confucius who advocates virtue based moral philosophy. His ideology centers around building moral character, social harmony and the cultivation of virtue through personal and collective development. The key characteristics of Confucian ethics include virtue ethics, relational ethics and self-cultivation. The core idea of virtue ethics revolves around self-development rather than implementing regulations. Along with that, relational ethics argues that morality is deeply rooted in social relationships, focusing duties within the society and self-cultivation preaches how moral development is a lengthy process which is based on learning, self-reflection and practice.",
      "The main components of Confucian theory include, De (righteous character), Dao (cultivating virtue), Yi (righteous knowledge), Ren (embodying righteous character), Li (good and proper actions) and Junzi (ideal person). To acquire these key concepts of Confucian theory an individual requires to have lifelong commitment towards self-cultivation, learning and moral discipline.",
      'Drawing on the case study, "Fighting Disinformation in the Palestine Conflict: The Role of Generative AI and Islamic Values", Confucian ethics views that the developers of generative AI should have become dutiful in order to ensure that utilization of AI related tools are not exploited to deceive and manipulate the public which can lead them to harm the society or disrupt the order. Spreading misinterpreted data and AI generated information against the respective religions has only fueled the conflict between Israel and Palestine.',
      "The main idea of Li refers to cultural norms and traditions that provide guidance to good behavior and build foundation for moral character and different social roles along with their responsibilities. Creating or allowing AI generated systems to produce fake images, videos, stories or scattering misinformation among the society goes against Li where the fundamental idea focuses on the social responsibilities related to their role. Under the lens of Confucius ethical theory, it would advocate in accordance with the traditional concept that individuals should opt practicing self-regulation and cultivate virtues to prevent suffering within the community, in respect of the role-based obligations. In Confucian perspective, disinformation by AI is not seen as a technical problem but rather seen as a failure which tends to threaten social harmony and dignity, as seen in the Israel-Palestine conflict.",
      "ANALYSIS OF THE CONFLICT WITH SOCRATIC METHOD",
      "The Socratic Method is developed by a Greek philosopher named Socrates, where the method refers to a form of philosophical inquiry and dialogue in order to explore various ethical concepts such as justice, virtue, courage, and good life. The key idea of the Socratic method revolves around several questions asked to the individual to bring them in the dialogue and refutation. These processes allow individuals to look into their beliefs and rationality in order to have a better perception of ethical values. Socrates firmly believed that through rigorous questioning individuals will be closer to moral truth and will be able to grasp a better clarity. Socratic method advocates through reasoned dialogue it helps to pursue profound comprehension regarding moral truths, challenge assumptions and cultivate personal virtue. According to the great Greek philosopher, ethical questioning is not only a theoretical concept rather it is a way of life to inspect logical explanation and rationality.",
      "In context to the Israel-Palestine conflict, application of the Socratic method would raise ethical questions regarding the moral duty of those who provide misinformation without verifying it. For deeper understanding and to dive into logical explanations Socrates method would analyse through reasoned questioning and inquire whether justice required no harm to others or not. Spreading fabricated information produced by AI, without verifying the truthfulness behind it, as a result individuals are misleading, misrepresenting and are moving towards injustice. Therefore, the foremost duty for the individuals is to seek true knowledge before sharing any information. Socrates' method would argue that this act shows lack of critical thinking and virtuousness within the individuals. Hence, before individuals follow this path, according to Socrates method they should go for self-examination and verify their knowledge before speaking or sharing.",
      "Moreover, to examine morality or rationality, another ethical question can be raised in context to this particular conflict, whether it is acceptable to use this AI generated disinformation for noble cause or not. Under Socratic ethics, a counter question will be asked to look for better clarity, that is, whether justice can be ever built on lies or falsehood. The traditional ethical theory argues that no is damaged or hurt if the decision follows the path of justice. Using misinformation regarding Palestine as found in the case study, provides severe defamation of the country while Israel was portrayed that they were the victims of the real conflict. Thus, using misinterpreted information never opts justice rather seeks injustice which at the end causes harm to the soul, even if the intention was for a noble cause or own benefit, this act is self-defeating and unethical as it does not promote virtue.",
    ],
    references: [
      "Confucius. (1979). The Analects (D. C. Lau, Trans.). https://antilogicalism.com/",
      "Plato. (2008). Laches (B. Jowett, Trans.). https://www.gutenberg.org/",
    ],
  },
  {
    name: "Naziba Khandker",
    id: "24305050",
    title: "AI's Role in Religious Leadership: A Critical Analysis",
    content: [
      'The increasing popularity of artificial intelligence(AI) has reshaped many aspects of life, religion being one of them. As AI has access to religious texts and offers spiritual counsel and even influence judgements on religious teachings, it might raise an ethical concern on how AI engages with fundamental traditions and values. In the case study of "Fighting Disinformation in the Palestine Conflict: The Role of Generative AI and Islamic Values" by Lakhani and Khan (2023), it helps to understand the capability of AI to influence different perspectives and spread both true and false information. Although the case study focuses on the use of AI in warfare, its information stimulates larger questions about AI\'s role in areas of ethics and religion. To answer the question "to what extent should AI be allowed to take religious leadership such as guidance or taking decisions?" Consequentialism and Feminist Ethics shall be used.',
      "ANALYSIS OF ISRAEL-PALESTINE CONFLICT WITH CONSEQUENTIALISM ETHICS",
      "From the view of consequentialism, especially in utilitarianism, the morality of an action is determined by the outcome of the action (Mill, 1861/2001). An action is morally right if the consequence is good, and wrong if the outcome is bad. Mill (1863) founded utilitarianism which is a branch of consequentialism. According to him, the purpose of morality is to maximise happiness and minimise sorrow. The principle of consequentialism are:",
      "Morality is determined by the consequence which means that an action is morally right only on the basis of its consequences.",
      "Happiness principle which is that an action is morally right when it provides great happiness to a majority number of people.",
      "Equality where everyone's happiness is equally prioritised without looking at personal relationships or status of a person.",
      "From the concept of consequentialism, permitting AI to carry out religious leadership duties is morally acceptable if only the result of it is good. It can also be said that AI can be a useful tool for many unprivileged people who do not have access to many religious resources. AI also has the ability to give deeper insight about religious texts with proper explanation, through deeper analysis of the data (Al-Masri & Abu-Ghazaleh, 2020). The accessibility of religious insight is more free now that we have AI to help us with knowledge which was once restricted through language.",
      "However, from the case study it can be seen that AI with religion has many negative consequences. As Lakhani & Khan (2023) says in the case study how misinformation has spread through AI generated texts and images in the Israel and Palestine conflict, which leads to results which are not good to the people. If an AI system is programmed in a specific way it can generate harmful and misconception of religious content, misguide individuals or promote ideologies which are not accurate according to the religious content. Even though AI can help people to get religious knowledge and spiritual support, consequentialism warms us that it can have many problems that could create issues such as lost trust, question beliefs and even harm a person's morals.",
      "ANALYSIS OF THE CONFLICT WITH FEMINIST AND FEMINISM ETHICS",
      "Feminism is a social and philosophical movement which tries to address the challenges such as inequalities, discrimination and oppression faced by women and other gender groups, from a long period of time. Mary Wollstonecraft, John Stuart Mill, Sojourner Truth, and Elizabeth Cady Stanton were the earliest feminist who pointed out the inequalities in many sectors such as education politics and other social roles, and also argued how the restricted structure prevented women from achieving development in many sectors (MacKay, 2019). Their effort led to the First Wave feminism which mainly focused on legal rights and democracy.",
      "In the case study, the topic of AI generated narratives (Lakhani and Khan, 2023) aligns with the fear of Feminist Ethics that it would replicate dominance based on the programing of the data. For example, AI systems which are trained on the basis of androcentric and colonial theological interpretation which might mimic and reinforce these biases and limit feminist or religious insights. Therefore, Feminist Ethics discourages AI deploying in spiritual and counseling without a proper system for inclusivity, sensitivity and accountability to diverse communities. Furthermore AI lacks qualities that Feminist Ethics emphasises on such as affective and situational knowledge. It can be argued that it would be a threat to spiritual support as it is not possible to replace relational care with an automated system.",
      "From this it can be drawn that AI's role in spiritual leadership is discouraged in both Consequentialism and Feminist Ethics. As Consequentialism warns about the negative result which includes lost trust, questioning religious beliefs and harm personal morals. And Feminist Ethics warns about the loss of care ethics, relational and sensitivity to context when AI replaces spiritual leadership.",
      "However, neither of the Ethical theories completely discourage the use of AI, rather advises to limit its use as they might have wrong information leading to negative outcomes. AI's use should be for factual religious queries and to access theological resources.",
    ],
    references: [
      "Mill, J. S. (1863). Utilitarianism. Parker, Son, and Bourn.",
      "Al-Masri, M., & Abu-Ghazaleh, N. (2020). AI-Based Translation Tools in Quranic Studies. Journal of Islamic Studies, 31(4), 453-467.",
      "Lakhani, M., & Khan, H. M. A. (2023). Fighting disinformation in the Palestine conflict: The role of generative AI and Islamic values. Al Misbah Research Journal, 3(4), 1-13. https://doi.org/10.5281/zenodo.",
      "MacKay, K. (2019). Feminism and feminist ethics. In S. Campbell (Ed.), Introduction to philosophy: Ethics (pp. 64–74). Rebus Community.",
    ],
  },
  {
    name: "Shehrin Haque Shawr",
    id: "24308036",
    title: "China's Policies in Xinjiang: An Ethical Analysis",
    content: [
      "Questions Raised",
      "Do China's policies in Xinjiang uphold the equal basic liberties of the Uighur population?",
      "Are Uighurs provided with fair equality in terms of education or employment or are these opportunities structurally skewed in favor of Han Chinese citizens?",
      "Do the Chinese policies respect the autonomy of Uighur Muslims or do they treat them as a means of national unity?",
      "The policies of the Chinese government in XinJiang, specifically regarding the Uighur Muslims have raised notable ethical concerns on an international level. While the state displays the agenda as a way of making sure of national progress and unification, many human rights organizations insist that these actions decrease basic freedom, impose systematic inequality along with suppressing cultural identification. John Rawls' Theory of Justice as well as Kantian deontology is applied in order to evaluate these policies in terms of justice and mortality.",
      'According to Rawls, the first principle of justice says that "each person is to have an equal right to the most extensive basic liberty compatible with a similar liberty for others" (Rawls, 1971). These liberties involve freedom of speech, religion, association along with conscience. But the evidence from Xinjiang indicates that these fundamental rights are not warranted to the Uighur Muslim population. The Chinese government has enforced strict restrictions on Islamic practices, for example fasting during Ramadan, wearing religious clothing or going to mosques. Additionally the state has built "re-education camps" where people are kept in custody without trial, brainwashed with state ideology, and coerced to give up their religious and cultural distinctiveness. From the perspective of Rawls, such restrictions are not defensible ethically. Rawls proclaims that the goal of justice is to build a society that people would choose under a "veil of ignorance" in which no one knows their place in society, ethnicity, or religion (Rawls, 1971, p. 12). No rational person in this hypothetical situation would agree with living in a society where the state can, on the basis of any random reason instead of a system, not allow them religious and cultural liberties based on identity. Thus, the lack of liberty of the Uighurs violates Rawls\' first principle and unravels structural injustice.',
      'Kantian deontology further reinforces this critique. The Categorical imperative of Immanuel Kant orders everyone to treat all persons "as ends in themselves" and never merely as means (Kant, 1785/1996). The use of surveillance and coercion by the Chinese government for including Uighurs into the nationalistic Han identity very clearly is indicative of treating them as a way of national unity and state security. While probably serving the interests of the majority, This utilitarian logic is unsuccessful in respecting the individual autonomy of the Uighurs, making it ethically not allowed under deontological ethics.',
      '2. Rawls\' second principle of justice sheds light on the importance of fair equality of opportunity. It states that "offices and positions must be open to everyone under conditions of fair equality of opportunity" (Rawls, 1971, p. 72). Even though China says that they have invested in the development and education in Xinjiang, many of these programs are applied in Mandarin Chinese, sidelining the language and culture of the Uighur population, including Uighur Muslims. Uighur students often have difficulties in educational institutions where their mother tongue is not practiced, hence decreasing their chances of succeeding to higher education or employment places.',
      "Employment chances in Xinjiang are not equal in a similar manner. Positions in government jobs and in enterprises owned by the state are given to Han Chinese migrants in a disproportionate manner, who are encouraged to move to the region. Even though the state showcases this as an economic inclusion, this often leads to economic marginalization of Uighurs.",
      "These policies fail the justice test if Rawls' framework is followed. A society that not only ensures formal access but equality in opportunity. Additionally Rawls' difference principle argues that inequalities are allowed only if they benefit the disadvantaged members of society (Rawls, 1971, p. 75). And still in Xinjiang, inequality is built in a way that disadvantages the already disadvantaged, in this case, Uighurs socially, financially as well as politically. These gaps further reinforce their marginalization.",
      'Marx and Engels would argue that such inequalities are an indication of class and structural dominating. In their Manifesto, they proclaim that "the executive of the modern state is but a committee for managing the common affairs of the whole bourgeoisie" (Marx & Engels, 1848/2002, p. 9). Even when China is a socialist state, Marxist analysis states that it still works through state mechanisms that strengthen control by the ethnic group that is dominant. In this perspective, opportunities aren\'t given out in a just manner, but exploited to keep up the domination over the Uighur minority which includes Uighur Muslims.',
      '3. Kantian deontology positions autonomy in a way that centers ethical action. Every rational agent, according to Kant, has inherent worth and the ability to govern themselves. Any rule that forces into rebellion or crumbles their ability to destroy themselves violates this principle. The policies in Xinjiang which include compulsory political re-education, religious oppression and monitoring underestimate the moral autonomy of Uighur Muslims. Instead of being treated as free and liberated people who are capable of making their own cultural and religious decisions, Uighurs Muslims are subjected to control based on ideology for the sake of "unity."',
      'From this point of view, the approach of China is deontologically faulty. The Uighur Muslim are not ends in themselves but are reduced to "instruments of state goals" which contradicts the very intention of Kantian ethics.',
      "Rawls also notifies against such instrumentalism in political systems. A society that is just must be built in a way that free and equal citizens would endorse. No one who comprehends Rawls' veil of ignorance would agree with a regime that commands cultural assimilation as a condition in the way of accessing rights and resources. For Rawls, justice needs mutual respect, and this respect is declined when policies make people get reduced to tools of state ideology.",
      "An analysis of China's policies in Xinjiang that revolves around justice unravels serious violations of ethics. From the perspective of Rawls', the Uighur population, which includes Muslims also declined to have equal liberties and fair chances, denying both principles of justice. The autonomy of Uighur Muslims from the deontological perception is not regarded and them being treated as tools of national cohesiveness violates the moral ground to treat all individuals with dignity. Even through the point of view of Marx and Engels, these policies are reflective of the domination of interest of one group under the disguise of unity. In searching for harmony by forcing, the Chinese state not only underestimates ethical principles but also makes the foundations of a just governance unstable.",
    ],
    references: [
      "Kant, I. (1996). Groundwork of the metaphysics of morals (M. Gregor, Trans.). Cambridge University Press. (Original work published 1785)",
      "Marx, K., & Engels, F. (2002). The Communist Manifesto. Penguin Classics. (Original work published 1848)",
      "Rawls, J. (1971). A theory of justice. Harvard University Press.",
    ],
  },
  {
    name: "Irina Sumaiya",
    id: "24301111",
    title: "Ethical Analysis of AI Surveillance of Uyghur Muslims",
    content: [
      "Artificial intelligence (AI) can revolutionize religious communities through its increased access to spiritual content, resources, and guidelines. However, its misuse raises major ethical concerns. As AI becomes deeply connected with public surveillance, it becomes important to critically reflect and oversee its ethical repercussions on religious communities. One of the most concerning examples is the state of the Uyghur Muslims in Xinjiang, China. To track and target their religious practices, facial recognition, activity monitoring, AI prediction systems using algorithms, biometric data and statistical analysis have been applied (Leibold, 2006). This raises an urgent ethical question: How can religious communities ensure that AI applications respect privacy and protect sensitive religious data from misuse? Next, we will explore how ethical theories- deontology, feminist ethics, and Rawls's theory of justice- address and analyze this abuse of AI by the Chinese government.",
      "ANALYSIS OF THE PERSECUTION OF UIGHUR MUSLIMS IN CHINA WITH DEONTOLOGICAL ETHICS",
      "From a deontological perspective, morality is rooted in duty and respect for persons. Immanuel Kant's principles, particularly the categorical imperative, advocates treating individuals as ends in themselves and not as means to an end (Velasquez, 2008). In the Uyghur case, AI technologies are used to suppress and control these individuals. Surveilling them in order to track worshippers and examine private and sensitive data for profiling based on their connection with religion violates Kant's moral duty to respect human autonomy, dignity and their right to religious freedom. Hence, this system is unethical since it normalizes oppression and uses religion as a tool to justify power and control tactics- believers are mistreated as threats and not as persons with rights- despite the state claiming to use this for public security.",
      "ANALYSIS OF THE PERSECUTION OF UIGHUR MUSLIMS IN CHINA WITH FEMINISM AND FEMINIST ETHICS",
      "Feminist ethics centers around caring, nurturing and emotional relationships- components that are often ignored in patriarchal societies- and challenges traditional ethical theories for prioritizing duty, rules and autonomy more than real-world experiences. These monitoring systems used to control and dehumanize people disproportionately affect marginalized communities like women and minorities. In the case of c women, they carry twice the burden and scars from oppression- as religious minorities and as women- deepening the existing social injustices. They are subjected to cultural suppression, genocide and invasion of their bodily autonomy. These include monitoring of their clothing, particularly headscarves, forced sterilizations, tracking their menstrual cycles and inspection of their intimate spaces. Statistics by the Chinese government reported that the birth rate in Uyghur majority areas fell by more than 60% due to forced contraception and abortions.",
      "Looking from a feminist perspective, the use of AI to restrict and restrain minorities reinforces male-dominated systems and state power structures, as explained by Mackay (2009). It focuses on the fact that the privacy of the Uyghur Muslims is being systematically violated and abused without any consequences. Moreover, feminists argue that it is essential to give voices to those affected and oppressed by patriarchal domination and prioritize the welfare of the community over theoretical rules (Mackay, 2009).",
      "ANALYSIS OF THE PERSECUTION OF UIGHUR MUSLIMS IN CHINA WITH RAWLS' THEORY OF JUSTICE",
      "John Rawls' theory of justice advocates for impartiality and integrity in social structures. This system is based on a thought experiment called the \"veil of ignorance\" aimed to promote fairness and bring justice. It involves designing societal laws through individuals from a position of complete ignorance about their status, wealth, power and beliefs. This thought process is central to Rawls' theory of justice which proposes to benefit society's least privileged individuals (Rawls, 1971). Another principle is an individual's right to equal basic liberties, including freedom of religion. If we were to judge the Chinese AI surveillance behind this veil, it would be unethical and immoral to create a system that not only denies them their basic religious freedom but oppresses, imprisons and forcibly assimilates based on an individual's religious identity.",
      "The Uyghur case is a stark reminder of how AI can be weaponized against religious minorities. As noted by Leibold (2006), the Chinese government maintains a system to punish and suppress the Uyghur Muslims from expressing religious freedom to subject them to an authoritarian rule. It clearly breaches global human rights laws and raises concerns regarding the development of any future AI systems for use in religious communities. It not only violates Kant's principles of duty and dignity but it also affirms systemic discrimination from a feminist view and fails Rawls' experiment to ensure justice. It is important for religious communities to raise their voices against the unethical use of AI and advocate for systems that respect religious freedom and privacy. Transparent AI governance must be involved to protect justice and prevent discrimination. For marginalized groups and women of all colors, it must be ensured that their voices are not silenced or their identity misrepresented to guarantee liberty and equality for all.",
    ],
    references: [
      "Leibold, J. (2006). Xinjiang and the Han: Ethnic separatism and authoritarian rule in China. Asian Ethnicity.",
      "Mackay, K. (2009). Feminism and feminist ethics. In Philosophy: A text with readings (pp. 64–74). Wadsworth.",
      "Rawls, J. (1971). A theory of justice. Harvard University Press.",
      "Velasquez, M. (2008). Philosophy: A text with readings (10th ed., pp. 455–463). Wadsworth.",
    ],
  },
  {
    name: "Shaoli Barua Megha",
    id: "24308013",
    title: "The Promise and Risk of AI: A Utilitarian View",
    content: [
      "Artificial Intelligence (AI) and generic information systems (IS) hold revolutionary potential for development in the Global South, particularly when combined with cultural sensitivity and ethical imagination. It significantly impacts economic and social development if they are crafted from participatory and sensitive-contextual designs, Walsham and Sahay argue. AI, localized, can be used for promoting greater access to health care, education, and open government, thus facilitating sustainable and equitable development and empowerment in the long term.In the utilitarian moral school of thought specifically, John Stuart Mill's technology will be moral if it promotes more happiness and causes as little pain as possible. From this view, moral AI that enhances the quality of life and increases the disparity is under the \"greatest happiness principle\" of Mill. The reverse is also possible: IS and AI can be utilized to entrench repression and eradicate human rights and cause harm at an unprecedented level in history.A stark example is China's application of AI-enhanced monitoring technology in Xinjiang to keep and oppress the Uyghur Muslims. According to Byler, the technology facilitates mass observation, discretionary confinement, and culture oppression, attacking freedom's preconditions at the heart of Mill's vision for human flourishing. These applications of AI are algorithmic authoritarianism, not empowerment miniaturizing technological possibility into tools for repression.This double promise of AI requires wise, ethical design with dignity, freedom, and social justice as its guiding ideals. Otherwise, AI can solidify structural inequality rather than destroying it. The moral imperative is clear: AI being created must prioritize people over power, and living over efficiency.From a utilitarian perspective, the use of AI surveillance to monitor and repress the Uyghur Muslims in Xinjiang contradicts the \"greatest happiness\" principle. Byler (2006)",
      "ANALYSIS OF THE PERSECUTION OF UIGHUR MUSLIMS IN CHINA WITH FEMINISM AND FEMINIST ETHICS",
      "Masculine ideology is central to gender relations and the construction of gender-based violence. As Men, Masculinities and Changing Power explains, masculinity is socially constructed by norms that emphasize control, dominance, and repression of feelings. Such norms sustain patriarchal institutions and are directly culpable for forms of gender-based violence. such as sexual harassment, intimate partner violence, and coercion. Violence is also employed widely as a means of men reasserting control, particularly when their previous social dominance is perceived to be under challenge.",
      "Above all, patriarchal institutions do not bestow benefits on all men. Marginalised groups of men racialised or economically disenfranchised men are denied the benefits of hegemonic masculinity. Exclusion in such a manner can lead to subordinating constructions of masculinity based on violence that further entrench gender-based violence. An intersectionality approach is needed to understand how race, class, and gender oppression intersect.Artificial Intelligence (AI) reflects and magnifies these dynamics. When developed within patriarchal or authoritarian contexts, AI technologies can be used to perpetuate structural inequalities. As Byler reveals, in Xinjiang, China uses AI-facilitated surveillance on Uyghur Muslims men specifically in the guise of national security. This is comparable to how AI can be deployed as an instrument to racialized masculinities, framing them as threats and deserving suppression.",
      "But AI also offers tools for change. Ethically designed systems can enable gender-based violence prevention, identify abusive online speech, and encourage gender-sensitive communication. Grounded in values of empathy, inclusivity, and rights, AI can be a change agent for dismantling toxic masculinity and constructing gender justice in virtual and everyday.But then again AI creates the fake information which causes conflict like in China the Uighur muslims are dominated but by AI it goes to an extreme and the situation becomes more worse.",
      "ANALYSIS OF THE PERSECUTION OF UIGHUR MUSLIMS IN CHINA WITH RAWLS' THEORY OF JUSTICE",
      'John Rawls\' Theory of Justice suppose there exists a moral obligation of fair societies to seek equality through the "veil of ignorance," in which policy is enacted with the presumption that one does not know the social status they hold. All wraps around it with the same basic freedoms and resource equality and opportunity. AI surveillance of Uyghur Muslims in Xinjiang, as described by Byler, disrespects such values in literal terms. In this case, AI technologies are employed to expand mass surveillance, arbitrary detention, and cultural erasure practices that disrespected fundamental rights and reinforce systemic discrimination. The technologies reinforce current hierarchies instead of pursuing justice. In a Rawlsian universe, these uses would be impermissible because they are not maximizing the good of the least advantaged and they erode equal liberty. Ethical AI has to be an agent of equity and dignity, not domination or oppression. Justice demands more than technological advancement, it demands humanity.',
      "According to John Rawls' Theory of Justice, social and political structures must benefit the least advantaged members of society. The deployment of AI to target and oppress the Uyghur Muslims fails this principle, as it perpetuates inequality and undermines basic liberties. Byler (2006)",
    ],
    references: [
      "Mill, J. S. (1863). Utilitarianism. Parker, Son, and Bourn.",
      "Rawls, J. (1971). A theory of justice. Harvard University Press.",
    ],
  },
]
